// <auto-generated />
using HotelListing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220226141418_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HotelListing.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Colombia",
                            ShortName = "CO"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Germany",
                            ShortName = "GE"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Spain",
                            ShortName = "SP"
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address 1",
                            CountryId = 1,
                            Name = "Name 1",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address 2",
                            CountryId = 1,
                            Name = "Name 2",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address 3",
                            CountryId = 1,
                            Name = "Name 3",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address 4",
                            CountryId = 2,
                            Name = "Name 4",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Address 5",
                            CountryId = 2,
                            Name = "Name 5",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 6,
                            Address = "Address 6",
                            CountryId = 3,
                            Name = "Name 6",
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
